### ISSUE TITLE
service name with whitespace is not parsed correctly

### ISSUE THREAD

**Issue by qrkourier** [openziti-incubator/zssh#21]
from: https://community.netfoundry.io/t/attempting-use-use-zssh-after-successfully-using-ssh-and-nf-console/139/11

> Using this command line
`./zssh -s “zssh service” -c zssh.json -d`
The debug output is …
>
>        INFO username set to: mkochanik
>        INFO targetIdentity set to: service”
>        FATAL service not found: “zssh
> It seems to be hating on the fact that my service “zssh service” has a space

**Comment by dovholuknf** [comment]
based on the output - it looks like 'smart quotes' are used here and that's "not right"... and causing the first param to be found as `“zssh` and the second to be `service”`

**Comment by qrkourier** [comment]
Same conclusion here with your prompting. Thank you! I've poked Jersey Mike back in the thread.
