### ISSUE TITLE
Support for MFA 

### ISSUE THREAD

**Issue by markamind** [openziti-incubator/zssh#29]
This would be a useful capability to add

**Comment by dovholuknf** [comment]
possibly interesting/relevant https://github.com/openziti-test-kitchen/zssh/issues/29 i've been working on this in my off cycles. I'm hoping to merge this functionality soon as i can.

Are you looking for TOTP? or OIDC support? or something else?

**Comment by dovholuknf** [comment]
closed by #37. There are still MFA ergonomics to work out. Removing MFA doesn't work, but you can now enable MFA on an identity from zssh.

![mfa-example](https://github.com/user-attachments/assets/c1221751-786e-4281-84a8-cae8d11bd6cb)
[docker-versions.txt](https://github.com/user-attachments/files/16386738/docker-versions.txt)
